# Generated by Django 5.2.14 on 2026-07-17 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=200, unique=True)),
                ('scheme_maturity_period', models.IntegerField(blank=True, null=True)),
                ('scheme_benefit', models.CharField(choices=[('no_wastage', 'No wastage'), ('no_making_charges', 'No making charges'), ('no_making_no_wastage', 'No making and no wastage'), ('x_plus_y', 'x+y installments (pay x + get y installment benefit)')], max_length=50)),
                ('scheme_installment_amount', models.IntegerField(blank=True, null=True)),
                ('x_value', models.PositiveIntegerField(blank=True, null=True)),
                ('y_value', models.PositiveIntegerField(blank=True, null=True)),
                ('payable_installments', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes_created', to='erp.users')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes_updated', to='erp.users')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSchemeEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_installments', models.PositiveIntegerField()),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('pending_installments', models.PositiveIntegerField(default=0)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('defaulted', 'Defaulted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.users')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_enrollments', to='erp.accountdetails')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='schemes.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeInstallment',
            fields=[
                ('installment_id', models.AutoField(primary_key=True, serialize=False)),
                ('installment_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='schemes.customerschemeenrollment')),
            ],
            options={
                'ordering': ['installment_no'],
                'unique_together': {('enrollment', 'installment_no')},
            },
        ),
        migrations.CreateModel(
            name='SchemeReceipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='schemes.schemeinstallment')),
            ],
        ),
    ]
