# Generated by Django 5.2.14 on 2026-08-06 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_cartitem_gst_percentage'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('razorpay_order_id', models.CharField(max_length=255, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_transactions', to='erp.accountdetails')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.customerschemeenrollment')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_transactions', to='schemes.schemeinstallment')),
            ],
        ),
    ]
