# Generated by Django 5.2.14 on 2026-08-21 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_schemetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemetransaction',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheme_transactions', to='schemes.scheme'),
        ),
        migrations.AlterField(
            model_name='schemetransaction',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_transactions', to='schemes.customerschemeenrollment'),
        ),
        migrations.AlterField(
            model_name='schemetransaction',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_transactions', to='schemes.schemeinstallment'),
        ),
    ]
