# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_coupons_cart_customeraddress_notifications_orders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="gst_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
