# Generated by Django 5.2.14 on 2026-08-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_cartitem_gst_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRates',
            fields=[
                ('current_rates_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_date', models.DateField()),
                ('rate_time', models.TimeField()),
                ('rate_9crt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_16crt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_18crt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_22crt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_24crt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('silver_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'current_rates',
                'managed': False,
            },
        ),
    ]
