# Generated by Django 5.2.14 on 2026-08-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
